"""Stable API-facing adapters.  Model implementation details stay out of routes."""
from datetime import datetime, timezone
from typing import Callable
from backend.app.schemas.contracts import BackhaulInput, ForecastInput, PortFilterInput, RiskInput, ServiceOutput


class ForecastAdapter:
    def run(self, request: ForecastInput) -> ServiceOutput:
        try:
            from backend.freight_forecasting.freight_forecaster import forecast_freight
            forecast = forecast_freight(request.route, request.vessel_class, days_ahead=7)
        except Exception as exc:
            return ServiceOutput(result={"status": "model_error", "route": request.route}, confidence=0.0, reasons=[f"Freight model unavailable: {exc}"], data_as_of=None)
        if forecast.get("status") != "success":
            return ServiceOutput(result=forecast, confidence=0.0, reasons=[forecast.get("message", "No matching historical freight benchmark is available for this route and vessel class.")], data_as_of=None)
        return ServiceOutput(result={**forecast, "best_charter_window": forecast["lowest_rate_date"], "indicative_rate": forecast["lowest_forecast_rate_usd_per_ton"]}, confidence=0.65, reasons=["Forecast is generated by the existing RandomForest freight model.", f"Latest historical benchmark is {forecast['latest_historical_date']}.", forecast["forecast_note"]], data_as_of=datetime.fromisoformat(forecast["latest_historical_date"]).replace(tzinfo=timezone.utc))


class PortFilterAdapter:
    def run(self, request: PortFilterInput) -> ServiceOutput:
        from backend.app.reference_data import physical_port
        viable, rejected = [], []
        v = request.vessel
        for port in request.candidate_ports:
            limits = physical_port(port)
            if not limits:
                rejected.append({"port": port, "reasons": ["No source-backed physical constraint record"]})
                continue
            failures = [name for value, name, field in ((v.draft_m, "draft", "max_draft_m"), (v.loa_m, "LOA", "max_loa_m"), (v.beam_m, "beam", "max_beam_m"), (v.dwt, "DWT", "max_dwt")) if value is not None and value > limits[field]]
            (rejected if failures else viable).append({"port": port, "reasons": failures} if failures else port)
        reasons = [f"{item['port']} rejected: exceeds {', '.join(item['reasons'])} limit." for item in rejected]
        if not reasons: reasons = ["All supplied ports pass physical limits from data/cleaned/port_constraints.csv."]
        return ServiceOutput(result={"viable_ports": viable, "rejected_ports": rejected, "constraint_source": "data/cleaned/port_constraints.csv"}, confidence=0.8 if viable else 0.55, reasons=reasons, data_as_of=None)


class BackhaulAdapter:
    def run(self, request: BackhaulInput) -> ServiceOutput:
        from backend.services.backhaul_matcher import find_backhaul_match
        try:
            matches = find_backhaul_match(request.destination_port, request.origin_region)
        except Exception as exc:
            return ServiceOutput(result={"matches": []}, confidence=0.0, reasons=[f"Backhaul data unavailable: {exc}"], data_as_of=None)
        return ServiceOutput(result={"matches": matches}, confidence=0.75 if matches else 0.4, reasons=["Matches use documented export commodities at the destination port." if matches else "No documented return cargo matches the requested origin region."], data_as_of=datetime.now(timezone.utc))


class RiskAdapter:
    def __init__(self, data_provider: Callable | None = None): self.data_provider = data_provider

    def run(self, request: RiskInput) -> ServiceOutput:
        from backend.services.risk_mitigation import engine as risk
        if request.vessel.lat is None or request.vessel.lon is None:
            return ServiceOutput(result={"action": "UNKNOWN"}, confidence=0.0, reasons=["Vessel latitude and longitude are required for risk assessment."], data_as_of=None)
        if request.destination not in risk.PORTS:
            return ServiceOutput(result={"action": "UNKNOWN"}, confidence=0.0, reasons=[f"Unknown risk-model port: {request.destination}."], data_as_of=None)
        if self.data_provider:
            data = self.data_provider()
        else:
            # Reuse the existing service's asynchronous refresh cache.  A cold start
            # remains explicitly unknown rather than being represented as safe.
            from backend.services.risk_mitigation import router as live_risk
            live_risk.start_risk_refresh()
            data = live_risk.STATE["data"] or risk.RiskData(gaps=["Live weather/cyclone snapshot is warming up; retry shortly."])
        decision = risk.assess_voyage(risk.Vessel(request.vessel.lat, request.vessel.lon, request.vessel.draft_m, request.eta, request.vessel.name), request.destination, data, auto_apply=None)
        result = {"action": decision.action, "mandatory": decision.action == "AUTO_REROUTE", "recommended_port": decision.recommended_port, "alternates": [a.port for a in decision.alternates], "data_gaps": decision.data_gaps}
        reasons = [reason.headline for reason in decision.reasons] or ["No active model risk trigger was found."]
        return ServiceOutput(result=result, confidence=0.9 if not decision.data_gaps else 0.45, reasons=reasons, data_as_of=datetime.now(timezone.utc))
